parameters:
  vmImage: ''
  buildConfiguration: ''
  projects: ''
  arguments: ''

jobs:
  - job: IntegrationTests
    displayName: Run integreation tests
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: DotNetCoreCLI@2
        displayName: Execute integration tests
        inputs:
          command: test
          projects: ${{ parameters.projects }}
          configuration: ${{ parameters.buildConfiguration }}
          arguments: >
            --verbosity normal
            ${{ parameters.arguments }}
          publishTestResults: true
