language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
branches:
  only:
  - develop
script:
  - sh -c "dotnet test test/Telegram.Bot.Tests.Integ/Telegram.Bot.Tests.Integ.csproj --configuration Release --list-tests"
  - sh -c "dotnet test test/Telegram.Bot.Tests.Integ/Telegram.Bot.Tests.Integ.csproj --configuration Release --no-build"
notifications:
  email: false

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose env vars)

## Environment Variables:

# TelegramBot_ApiToken                      test-bot-api-token
# TelegramBot_AllowedUserNames              main_tester,some_other_user
# TelegramBot_SuperGroupChatId              -1234
# TelegramBot_PaymentProviderToken          token-from-stripe-test-bot
# TelegramBot_TesterPrivateChatId           1234
# TelegramBot_RegularMemberUserId           9876
# TelegramBot_RegularMemberUserName         main_tester
# TelegramBot_RegularMemberPrivateChatId    9876
